## CLASS PATH API
server.servlet.context-path=/best_travel

## DATASOURCE
spring.datasource.url=jdbc:postgresql://localhost:5432/best_travel
spring.datasource.username=admin
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.type.descriptor.sql.BasicBinder=TRACE